Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-12"
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.define "rgeralS" do |master|
    master.vm.hostname = "rgeralS"
    master.vm.network :private_network, ip: "192.168.56.110"
    master.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    master.vm.provision "shell", privileged: true, path: "scripts/k3s_master.sh", args: ["192.168.56.110"]

    master.vm.provider "virtualbox" do |v|
      v.name = "rgeralS"
    end
  end

  config.vm.define "rgeralSW" do |worker|
    worker.vm.hostname = "rgeralSW"
    worker.vm.network :private_network, ip: "192.168.56.111" 
    worker.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    worker.vm.provision "shell", privileged: true, path: "scripts/k3s_worker.sh", args: ["192.168.56.110", "192.168.56.111"]

    worker.vm.provider "virtualbox" do |v|
      v.name = "rgeralSW"
    end
  end
end
